name: Copy dist/ to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Build site
        run: ./build.sh
    
      - name: Check dist contents
        run: ls -la dist
    
      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch gh-pages || git switch --orphan gh-pages
          rm -rf ./*
          cp -r dist/* ./
          git add .
          git commit -m "Deploy from main" || echo "No changes to commit"
          git push origin gh-pages --force

