name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # allow pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build site
        run: |
          rm -rf dist
          mkdir dist
          bash build.sh

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.BUILD_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
